name: CI Build

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-publish:
    runs-on:
      group: homelab-build
      labels: [docker,dotnet,prosoft]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
